config/routes.rb
DemoApp::Application.routes.draw do
  resources :noises

  resources :beasts

end

app/models/beast.rb
class Beast < ActiveRecord::Base
  has_many :noises
end

app/models/noise.rb
class Noise < ActiveRecord::Base
  belongs_to :beast
  validates :sound, :length => { :maximum => 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beasts_controller.rb
class BeastsController < ApplicationController
  # GET /beasts
  # GET /beasts.json
  def index
    @beasts = Beast.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beasts }
    end
  end

  # GET /beasts/1
  # GET /beasts/1.json
  def show
    @beast = Beast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beast }
    end
  end

  # GET /beasts/new
  # GET /beasts/new.json
  def new
    @beast = Beast.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beast }
    end
  end

  # GET /beasts/1/edit
  def edit
    @beast = Beast.find(params[:id])
  end

  # POST /beasts
  # POST /beasts.json
  def create
    @beast = Beast.new(params[:beast])

    respond_to do |format|
      if @beast.save
        format.html { redirect_to @beast, notice: 'Beast was successfully created.' }
        format.json { render json: @beast, status: :created, location: @beast }
      else
        format.html { render action: "new" }
        format.json { render json: @beast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beasts/1
  # PUT /beasts/1.json
  def update
    @beast = Beast.find(params[:id])

    respond_to do |format|
      if @beast.update_attributes(params[:beast])
        format.html { redirect_to @beast, notice: 'Beast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beasts/1
  # DELETE /beasts/1.json
  def destroy
    @beast = Beast.find(params[:id])
    @beast.destroy

    respond_to do |format|
      format.html { redirect_to beasts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/noises_controller.rb
class NoisesController < ApplicationController
  # GET /noises
  # GET /noises.json
  def index
    @noises = Noise.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @noises }
    end
  end

  # GET /noises/1
  # GET /noises/1.json
  def show
    @noise = Noise.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @noise }
    end
  end

  # GET /noises/new
  # GET /noises/new.json
  def new
    @beasts = Beast.all
    @noise = Noise.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @noise }
    end
  end

  # GET /noises/1/edit
  def edit
    @noise = Noise.find(params[:id])
  end

  # POST /noises
  # POST /noises.json
  def create
    @noise = Noise.new(params[:noise])

    respond_to do |format|
      if @noise.save
        format.html { redirect_to @noise, notice: 'Noise was successfully created.' }
        format.json { render json: @noise, status: :created, location: @noise }
      else
        format.html { render action: "new" }
        format.json { render json: @noise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /noises/1
  # PUT /noises/1.json
  def update
    @noise = Noise.find(params[:id])

    respond_to do |format|
      if @noise.update_attributes(params[:noise])
        format.html { redirect_to @noise, notice: 'Noise was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @noise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noises/1
  # DELETE /noises/1.json
  def destroy
    @noise = Noise.find(params[:id])
    @noise.destroy

    respond_to do |format|
      format.html { redirect_to noises_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beasts_helper.rb
module BeastsHelper
end

app/helpers/noises_helper.rb
module NoisesHelper
end

app/views/beasts/_form.html.erb
<%= form_for(@beast) do |f| %>
  <% if @beast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beast.errors.count, "error") %> prohibited this beast from being saved:</h2>

      <ul>
      <% @beast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beasts/edit.html.erb
<h1>Editing beast</h1>

<%= render 'form' %>

<%= link_to 'Show', @beast %> |
<%= link_to 'Back', beasts_path %>

app/views/beasts/index.html.erb
<h1>Listing beasts</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beasts.each do |beast| %>
  <tr>
    <td><%= beast.name %></td>
    <td><%= link_to 'Show', beast %></td>
    <td><%= link_to 'Edit', edit_beast_path(beast) %></td>
    <td><%= link_to 'Destroy', beast, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beast', new_beast_path %>

app/views/beasts/new.html.erb
<h1>New beast</h1>

<%= render 'form' %>

<%= link_to 'Back', beasts_path %>

app/views/beasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Beast Name:</b>
  <%= @beast.name %>
</p>
<p>
	<b>Noises:</b><br/>
	<% @beast.noises.each do |noise| %>
	<%= noise.sound %><br/>
	<% end %>
</p>


<%= link_to 'Edit', edit_beast_path(@beast) %> |
<%= link_to 'Back', beasts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/noises/_form.html.erb
<%= form_for(@noise) do |f| %>
  <% if @noise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@noise.errors.count, "error") %> prohibited this noise from being saved:</h2>

      <ul>
      <% @noise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sound %><br />
    <%= f.text_field :sound %>
  </div>
  <%= collection_select(:noise, :beast_id, @beasts, :id, :name) %>
  <div class="field">
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/noises/edit.html.erb
<h1>Editing noise</h1>

<%= render 'form' %>

<%= link_to 'Show', @noise %> |
<%= link_to 'Back', noises_path %>

app/views/noises/index.html.erb
<h1>Listing noises</h1>

<table>
  <tr>
    <th>Sound</th>
    <th>Beast</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @noises.each do |noise| %>
  <tr>
    <td><%= noise.sound %></td>
    <td><%= noise.beast_id %></td>
    <td><%= link_to 'Show', noise %></td>
    <td><%= link_to 'Edit', edit_noise_path(noise) %></td>
    <td><%= link_to 'Destroy', noise, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Noise', new_noise_path %>

app/views/noises/new.html.erb
<h1>New noise</h1>

<%= render 'form' %>

<%= link_to 'Back', noises_path %>

app/views/noises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sound:</b>
  <%= @noise.sound %>
</p>

<p>
  <b>Beast:</b>
  <%= @noise.beast_id %>
</p>


<%= link_to 'Edit', edit_noise_path(@noise) %> |
<%= link_to 'Back', noises_path %>